Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 67, in execute
    loop.run_until_complete(future)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 105, in build
    return await extension.build(additional_hooks=additional_hooks)
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 81, in build
    available_commands = await self._get_available_commands(
  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 171, in _get_available_commands
    output = await check_output(
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 128, in check_output
    assert not rc, f'Expected {args} to pass: {stderr_data}'
AssertionError: Expected ['/usr/bin/python3', 'setup.py', '--help-commands'] to pass: Traceback (most recent call last):
  File "/home/burger/CS-7785/lab_3/team13_chase_object/setup.py", line 5, in <module>
    setup(
  File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 172, in setup
    ok = dist.parse_command_line()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 472, in parse_command_line
    if self.handle_display_options(option_order):
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1209, in handle_display_options
    return _Distribution.handle_display_options(self, option_order)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 686, in handle_display_options
    self.print_commands()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 988, in print_commands
    cmdclass = ep.load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/develop.py", line 8, in <module>
    from setuptools.command.easy_install import easy_install
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 50, in <module>
    from setuptools.sandbox import run_setup
  File "/usr/local/lib/python3.10/dist-packages/setuptools/sandbox.py", line 13, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3328, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 622, in _build_master
    ws = cls()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 615, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 671, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2134, in find_on_path
    for dist in factory(fullpath):
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2199, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2673, in from_location
    )._reload_version()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 3081, in _reload_version
    md_version = self._get_version()
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2858, in _get_version
    version = _version_from_file(lines)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2624, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2853, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1529, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1521, in get_metadata
    return value.decode('utf-8')
KeyboardInterrupt

